name: handwerker_web
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  dio: ^5.4.1
  firebase_core: ^2.29.0
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0

  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  intl: any
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  syncfusion_flutter_calendar: ^25.2.4
  calendar_view: ^1.2.0
  pdf: ^3.10.8
  path_provider: ^2.1.3
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
